/**
 * Merging our entry into a workspace's existing Claude Code config.
 *
 * Kept pure and free of vscode imports so it can be tested: this code edits
 * files the user did not create and may have hand-tuned, so "preserve
 * everything I do not own, and refuse rather than guess" is the whole contract.
 */

export interface McpServerEntry {
  command: string;
  args: string[];
  env?: Record<string, string>;
}

export type MergeResult =
  | { ok: true; json: string; replacedExisting: boolean; siblings: string[] }
  | { ok: false; reason: string };

function isPlainObject(v: unknown): v is Record<string, unknown> {
  return typeof v === 'object' && v !== null && !Array.isArray(v);
}

/**
 * Add `name` to an existing `.mcp.json`, leaving every other server and every
 * unrelated top-level key untouched.
 *
 * `existingText` must be undefined only when the file genuinely does not exist.
 * A file that exists but cannot be parsed returns `ok: false` — overwriting it
 * would silently delete the user's other MCP servers.
 */
export function mergeMcpConfig(
  existingText: string | undefined,
  name: string,
  entry: McpServerEntry,
): MergeResult {
  let root: Record<string, unknown>;

  if (existingText === undefined || existingText.trim() === '') {
    root = {};
  } else {
    let parsed: unknown;
    try {
      parsed = JSON.parse(existingText);
    } catch (e) {
      return {
        ok: false,
        reason: `.mcp.json is not valid JSON (${(e as Error).message}). Fix or remove it first — overwriting it would drop your other MCP servers.`,
      };
    }
    if (!isPlainObject(parsed)) {
      return { ok: false, reason: '.mcp.json does not contain a JSON object.' };
    }
    root = parsed;
  }

  if (root.mcpServers !== undefined && !isPlainObject(root.mcpServers)) {
    return { ok: false, reason: '.mcp.json has an "mcpServers" key that is not an object.' };
  }

  const servers = isPlainObject(root.mcpServers) ? { ...root.mcpServers } : {};
  const replacedExisting = Object.prototype.hasOwnProperty.call(servers, name);
  const siblings = Object.keys(servers).filter((k) => k !== name);
  servers[name] = entry;

  return {
    ok: true,
    json: JSON.stringify({ ...root, mcpServers: servers }, null, 2) + '\n',
    replacedExisting,
    siblings,
  };
}

/**
 * Stamped into the generated slash command so re-running setup can tell its own
 * output from a `/review` command the user wrote themselves.
 */
export const COMMAND_MARKER = '<!-- generated by markdown-claude-review -->';

export function isOurCommand(text: string): boolean {
  return text.includes(COMMAND_MARKER);
}
